import { Clock, PauseCircle, Zap } from 'lucide-react';
import { serverFetch } from '@/lib/server-api';
import type { AutomationSummary } from '@/lib/api-types';
import { Badge } from '@/components/ui/badge';
import { Card } from '@/components/ui/card';
import { FadeIn } from '@/components/motion';

export const metadata = { title: 'Automation · BUILDR' };

/**
 * What the system does on its own.
 *
 * This page exists because unattended work has to be visible. The nightly job drafts wage
 * periods into the account with nobody logged in — an owner who finds a sheet they did not
 * create should be able to read here what runs, when, and what it touches, instead of
 * concluding that somebody else has access to their account.
 *
 * The job that writes records says so in its own panel. The three that only send messages are
 * listed plainly; nothing about them changes a figure anyone has to check.
 */
export default async function AutomationPage() {
  const automation = await serverFetch<AutomationSummary>('/automation');
  const writing = automation.jobs.filter((job) => job.effect !== null);
  const sending = automation.jobs.filter((job) => job.effect === null);

  return (
    <FadeIn className="flex flex-col gap-5">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <p className="max-w-xl text-[13.5px] leading-relaxed text-ink-muted">
          These run without anybody signed in. Times are {automation.timezone.replace('_', ' ')},
          the same clock your sites work to — a summary that says &ldquo;today&rdquo; means your
          today, wherever the server happens to be.
        </p>
        {automation.jobs_enabled ? (
          <Badge tone="done">Running</Badge>
        ) : (
          <Badge tone="pending">Paused</Badge>
        )}
      </div>

      {!automation.jobs_enabled && (
        <Card className="flex items-start gap-3 p-4">
          <PauseCircle className="mt-0.5 size-5 flex-none text-pending-fg" />
          <div className="flex flex-col gap-1">
            <span className="text-[14px] font-semibold">Nothing is running right now</span>
            <span className="text-[13px] leading-relaxed text-ink-muted">
              Background jobs are switched off on this deployment, so none of the schedules below
              will fire. Wage sheets have to be generated by hand until they are turned back on.
            </span>
          </div>
        </Card>
      )}

      {writing.length > 0 && (
        <section className="flex flex-col gap-2.5">
          <span className="text-[12px] font-semibold uppercase tracking-[0.08em] text-ink-muted">
            Creates records for you
          </span>
          {writing.map((job) => (
            <Card key={job.key} className="flex flex-col gap-3 p-4">
              <div className="flex flex-wrap items-start justify-between gap-3">
                <div className="flex min-w-0 flex-col gap-1">
                  <span className="flex items-center gap-2 text-[15px] font-semibold leading-snug">
                    <Zap className="size-4 text-accent" />
                    {job.name}
                  </span>
                  <span className="text-[13.5px] leading-relaxed text-ink-muted">
                    {job.description}
                  </span>
                </div>
                <ScheduleStamp
                  readable={job.readable}
                  cron={job.cron}
                  nextRun={job.next_run}
                  enabled={job.enabled}
                />
              </div>
              <p className="rounded-btn bg-accent-soft px-3 py-2 text-[13px] leading-relaxed text-ink">
                {job.effect}
              </p>
            </Card>
          ))}
        </section>
      )}

      <section className="flex flex-col gap-2.5">
        <span className="text-[12px] font-semibold uppercase tracking-[0.08em] text-ink-muted">
          Sends messages only
        </span>
        <Card className="divide-y divide-line-soft">
          {sending.map((job) => (
            <div key={job.key} className="flex flex-wrap items-start justify-between gap-3 p-4">
              <div className="flex min-w-0 flex-col gap-1">
                <span className="text-[14.5px] font-medium leading-snug">{job.name}</span>
                <span className="text-[13px] leading-relaxed text-ink-muted">
                  {job.description}
                </span>
              </div>
              <ScheduleStamp
                readable={job.readable}
                cron={job.cron}
                nextRun={job.next_run}
                enabled={job.enabled}
              />
            </div>
          ))}
        </Card>
      </section>
    </FadeIn>
  );
}

/**
 * When a job runs.
 *
 * Falls back to the raw cron when the pattern is not a plain daily one. A wrong plain-English
 * description of when something fires is worse than showing the expression and letting whoever
 * set it read it back.
 */
function ScheduleStamp({
  readable,
  cron,
  nextRun,
  enabled,
}: {
  readable: string | null;
  cron: string;
  nextRun: string | null;
  enabled: boolean;
}) {
  return (
    <div className="flex flex-none flex-col items-end gap-0.5">
      <span className="flex items-center gap-1.5 text-[13px] font-medium">
        <Clock className="size-3.5 text-ink-faint" />
        {readable ?? <code className="font-mono text-[12.5px]">{cron}</code>}
      </span>
      {enabled && nextRun ? (
        <span className="font-mono text-[12px] text-ink-muted">
          next{' '}
          {new Intl.DateTimeFormat('en-IN', {
            weekday: 'short',
            day: 'numeric',
            month: 'short',
            hour: 'numeric',
            minute: '2-digit',
            hour12: true,
            timeZone: 'Asia/Kolkata',
          }).format(new Date(nextRun))}
        </span>
      ) : (
        <span className="text-[12px] text-ink-faint">not scheduled</span>
      )}
    </div>
  );
}
