-- Align the client-portal foreign keys with what the datamodel declares.
--
-- The four tables added by hand for the conversation, read receipts and documents declared their
-- foreign keys with `ON DELETE ...` and no `ON UPDATE` clause, so Postgres defaulted them to
-- ON UPDATE NO ACTION. Prisma emits ON UPDATE CASCADE for every relation, so `migrate diff` saw the
-- migrations and schema.prisma describing different databases and the CI drift check failed.
--
-- Nothing observable changes: these are UUID primary keys generated by the database, and a primary
-- key that never changes has no update to cascade. It matters because the drift check is the thing
-- that catches the migration somebody forgets to write, and a check that cries wolf gets ignored —
-- and because the next `prisma migrate dev` on a drifting schema offers to reset the database.
--
-- Forward-only rather than editing the four migrations in place: they are applied already, and a
-- developer's local database full of test data should not have to be rebuilt to pick this up.

-- DropForeignKey
ALTER TABLE "documents" DROP CONSTRAINT "documents_project_id_fkey";

-- DropForeignKey
ALTER TABLE "documents" DROP CONSTRAINT "documents_tenant_id_fkey";

-- DropForeignKey
ALTER TABLE "documents" DROP CONSTRAINT "documents_uploaded_by_fkey";

-- DropForeignKey
ALTER TABLE "site_message_attachments" DROP CONSTRAINT "site_message_attachments_message_id_fkey";

-- DropForeignKey
ALTER TABLE "site_message_attachments" DROP CONSTRAINT "site_message_attachments_tenant_id_fkey";

-- DropForeignKey
ALTER TABLE "site_message_reads" DROP CONSTRAINT "site_message_reads_project_id_fkey";

-- DropForeignKey
ALTER TABLE "site_message_reads" DROP CONSTRAINT "site_message_reads_tenant_id_fkey";

-- DropForeignKey
ALTER TABLE "site_message_reads" DROP CONSTRAINT "site_message_reads_user_id_fkey";

-- DropForeignKey
ALTER TABLE "site_messages" DROP CONSTRAINT "site_messages_author_id_fkey";

-- DropForeignKey
ALTER TABLE "site_messages" DROP CONSTRAINT "site_messages_project_id_fkey";

-- DropForeignKey
ALTER TABLE "site_messages" DROP CONSTRAINT "site_messages_recipient_id_fkey";

-- DropForeignKey
ALTER TABLE "site_messages" DROP CONSTRAINT "site_messages_tenant_id_fkey";

-- AddForeignKey
ALTER TABLE "site_messages" ADD CONSTRAINT "site_messages_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "site_messages" ADD CONSTRAINT "site_messages_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "site_messages" ADD CONSTRAINT "site_messages_author_id_fkey" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "site_messages" ADD CONSTRAINT "site_messages_recipient_id_fkey" FOREIGN KEY ("recipient_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "site_message_attachments" ADD CONSTRAINT "site_message_attachments_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "site_message_attachments" ADD CONSTRAINT "site_message_attachments_message_id_fkey" FOREIGN KEY ("message_id") REFERENCES "site_messages"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "site_message_reads" ADD CONSTRAINT "site_message_reads_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "site_message_reads" ADD CONSTRAINT "site_message_reads_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "site_message_reads" ADD CONSTRAINT "site_message_reads_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "documents" ADD CONSTRAINT "documents_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "documents" ADD CONSTRAINT "documents_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "documents" ADD CONSTRAINT "documents_uploaded_by_fkey" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

